sudo: false
language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: me@refack.com
  api_key:
    secure: i/b/3QFSpstNAqMoq13qmXGDikK6JPhr9S+psNH6W+pcEkmFZzdo9LyWy2ki5z4ngQFMx0yrhiROjEZtiwIb0xBdt4N+XFIOQqGlhjcwg14G2kk8lL5sRfL0RD8nH95xg499X3mEiqKWOcWeEh/iPWO5TboDm8CvCgW4sez+jn4=
  on:
    tags: true
    repo: TheNodeILs/asynctrace
